remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: true
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: true
 other: true
 volunteer: false

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Software developer

locations:
  - Italy

distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2
